apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: cert-manager@devmem.ru
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
      - dns01:
          webhook:
            groupName: acme.selectel.ru
            solverName: selectel
            config:
              dnsSecretRef:
                name: selectel-dns-credentials
        selector:
          dnsZones:
            - "devmem.ru"
            - "home.devmem.ru"
            - "k8s.devmem.ru"
            - "tele.devmem.ru"
