loki-stack:
  loki:
    fullnameOverride: loki
    isDefault: false
    config:
      existingSecret: loki
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: &host loki.k8s.devmem.ru
          paths:
            - /
      tls:
        - hosts:
            - *host
          secretName: null
    persistence:
      enabled: true
      storageClassName: longhorn
      size: 5Gi
    serviceMonitor:
      enabled: true
  promtail:
    enabled: false
