apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki
  labels:
    {{- include "loki.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    template:
      data:
        loki.yaml: |
          auth_enabled: false
          compactor:
            retention_enabled: true
            shared_store: s3
            working_directory: /data/loki/compactor
          ingester:
            lifecycler:
              ring:
                replication_factor: 1
            wal:
              dir: /data/loki/wal
          limits_config:
            enforce_metric_name: false
            retention_period: 30d
          memberlist:
            abort_if_cluster_join_fails: false
            join_members:
              - loki-memberlist
          query_scheduler:
            max_outstanding_requests_per_tenant: 2048
          schema_config:
            configs:
              - from: "2020-10-24"
                store: boltdb-shipper
                object_store: s3
                schema: v12
                index:
                  prefix: v12_index_
                  period: 24h
          server:
            grpc_listen_port: 9095
            http_listen_port: 3100
            grpc_server_max_recv_msg_size: 8388608
            grpc_server_max_send_msg_size: 8388608
          storage_config:
            aws:
              endpoint: s3.home.devmem.ru
              bucketnames: loki
              access_key_id: {{ `{{ .s3Key }}` }}
              secret_access_key: {{ `{{ .s3KeySecret }}` }}
              s3forcepathstyle: true
            boltdb_shipper:
              active_index_directory: /data/loki/index
              cache_location: /data/loki/index_cache
              shared_store: s3
  data:
    - secretKey: s3Key
      remoteRef:
        key: secret/loki
        property: s3-key
    - secretKey: s3KeySecret
      remoteRef:
        key: secret/loki
        property: s3-key-secret
