jackett:
  image:
    repository: ghcr.io/k8s-at-home/jackett
    tag: v0.20.1825
  env:
    TZ: Europe/Moscow
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: &host jackett.home.devmem.ru
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
  persistence:
    config:
      enabled: true
      type: pvc
      accessMode: ReadWriteOnce
      storageClass: longhorn
      size: 1Gi
  resources:
    requests:
      cpu: 10m
      memory: 200Mi
    limits:
      cpu: 100m
      memory: 256Mi
