---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-config
  labels:
    app.kubernetes.io/name: tautulli
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
  volumeName: tautulli-config
