vpa:
  recommender:
    image:
      repository: k8s.gcr.io/autoscaling/vpa-recommender
      tag: 0.12.0
    extraArgs:
      pod-recommendation-min-cpu-millicores: 10
      pod-recommendation-min-memory-mb: 10
      prometheus-address: http://kps-prometheus.observability.svc.cluster.local:9090
      storage: prometheus
      prometheus-cadvisor-job-name: kubelet
      metric-for-pod-labels: kube_pod_labels{job="kube-state-metrics"}[8d]
      pod-namespace-label: namespace
      pod-name-label: pod
      container-namespace-label: namespace
      container-pod-name-label: pod
      container-name-label: container
  updater:
    enabled: false
