renovate:
  cronjob:
    schedule: "0 5 * * *"
  renovate:
    config: |
      {
        "extends": [
          "config:recommended",
          ":disableRateLimiting"
        ],
        "platform": "gitea",
        "endpoint": "https://git.devmem.ru/",
        "autodiscover": true,
        "printConfig": false,
        "dependencyDashboardTitle": "Renovate Dashboard",
        "detectHostRulesFromEnv": true,
        "commitBodyTable": true,
        "pre-commit": {
          "enabled": true
        },
        "packageRules": [
          {
            "matchManagers": ["pre-commit"],
            "groupName": "pre-commit"
          }
        ]
      }
  existingSecret: renovate
