descheduler:
  schedule: "*/5 * * * *"
  deschedulerPolicy:
    maxNoOfPodsToEvictPerNode: 2
    maxNoOfPodsToEvictPerNamespace: 2
    strategies:
      RemoveDuplicates:
        enabled: true
      RemovePodsViolatingNodeTaints:
        enabled: true
      RemovePodsViolatingNodeAffinity:
        enabled: true
        params:
          nodeAffinityType:
            - requiredDuringSchedulingIgnoredDuringExecution
      RemovePodsViolatingInterPodAntiAffinity:
        enabled: true
      LowNodeUtilization:
        enabled: true
        params:
          nodeFit: true
          nodeResourceUtilizationThresholds:
            thresholds:
              cpu: 40
              memory: 30
              pods: 25
            targetThresholds:
              cpu: 75
              memory: 50
              pods: 50
          namespaces:
            exclude:
              - "longhorn-system"
              - "metallb-system"
      RemovePodsHavingTooManyRestarts:
        enabled: true
        params:
          podsHavingTooManyRestarts:
            podRestartThreshold: 10
            includingInitContainers: true
      RemoveFailedPods:
        enabled: true
        params:
          failedPods:
            includingInitContainers: true
            excludeOwnerKinds:
              - Job
            minPodLifetimeSeconds: 3600
