teleport-cluster:
  chartMode: standalone
  clusterName: tele.devmem.ru
  kubeClusterName: infra
  authentication:
    type: local
    secondFactor: otp
  proxyListenerMode: multiplex
  persistence:
    enabled: true
    volumeSize: 5Gi
  highAvailability:
    certManager:
      enabled: true
      issuerName: letsencrypt-prod
      issuerKind: ClusterIssuer
      issuerGroup: cert-manager.io
  service:
    type: LoadBalancer
    spec:
      loadBalancerIP: 192.168.13.241
  podSecurityPolicy:
    enabled: false
  podMonitor:
    enabled: true
