---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deluge
  labels:
    app.kubernetes.io/name: deluge
data:
  VPN_ENABLED: "yes"
  VPN_PROV: custom
  VPN_CLIENT: wireguard
  ENABLE_PRIVOXY: "no"
  LAN_NETWORK: 10.244.0.0/16,192.168.0.0/16
  NAME_SERVERS: 10.44.0.1,1.1.1.1
  DELUGE_DAEMON_LOG_LEVEL: info
  DELUGE_WEB_LOG_LEVEL: info
  DEBUG: "false"
  UMASK: "022"
  PUID: "1000"
  PGID: "1000"
