---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: deluge-wireguard
  labels:
    app.kubernetes.io/name: deluge
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    template:
      data:
        wg0.conf: |
          [Interface]
          PrivateKey = {{ .wgPrivateKey }}
          Address = 10.255.255.40/24
          PostUp = '/root/wireguardup.sh'
          PostDown = '/root/wireguarddown.sh'

          [Peer]
          PublicKey = ptgafvY1m2aj4FKFwBCeEVylpPjaynqEYm0tQyR3P2c=
          AllowedIPs = 0.0.0.0/0
          Endpoint = vps-sd-ams.devmem.ru:51820
  data:
    - secretKey: wgPrivateKey
      remoteRef:
        key: secret/deluge
        property: wg-private-key
