---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluge-config
  labels:
    app.kubernetes.io/name: deluge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
