apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-datasource
  labels:
    grafana_datasource: "1"
data:
  thanos-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        isDefault: true
        url: http://thanos-query:9090/
