longhorn:
  defaultSettings:
    defaultReplicaCount: 2
    nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
    fastReplicaRebuildEnabled: true
    replicaAutoBalance: best-effort
    removeSnapshotsDuringFilesystemTrim: true
    concurrentAutomaticEngineUpgradePerNodeLimit: 1
    backupTarget: s3://longhorn@minio/
    backupTargetCredentialSecret: longhorn-backup
    nodeDrainPolicy: allow-if-replica-is-stopped
  persistence:
    defaultClass: true
    defaultClassReplicaCount: 2
    reclaimPolicy: Retain
    recurringJobSelector:
      enable: true
      jobList: '[{"name": "snapshot-default", "isGroup": false}, {"name": "backup-default", "isGroup": false}, {"name": "fs-trim-default", "isGroup": false}]'
  longhornUI:
    replicas: 1
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "10G"
      nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    host: longhorn.k8s.devmem.ru
    tls: true
    tlsSecret: null
  metrics:
    serviceMonitor:
      enabled: true
