gitlab-runner:
  revisionHistoryLimit: 2
  gitlabUrl: https://gitlab.com
  unregisterRunners: true
  concurrent: 5
  rbac:
    create: true
    rules:
      - apiGroups: [""]
        resources: ["*"]
        verbs: ["*"]
  runners:
    secret: gitlab-runner
    config: |
      [[runners]]
        [runners.kubernetes]
          image = "alpine:3.18"
        [runners.cache]
          Type = "s3"
          Path = "gitlab-runner"
          Shared = true
          [runners.cache.s3]
            ServerAddress = "s3.home.devmem.ru"
            BucketName = "gitlab"
            BucketLocation = "main"
  secrets:
    - name: s3access
