flaresolverr:
  image:
    repository: flaresolverr/flaresolverr
    tag: v3.3.16
  env:
    TZ: Europe/Moscow
    LOG_LEVEL: info
    LOG_HTML: "false"
    CAPTCHA_SOLVER: none
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
