apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - all.yaml
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: goldilocks-controller
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/resources/limits/cpu
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: goldilocks-dashboard
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/resources/limits/cpu
