dex:
  configSecret:
    create: false
    name: dex
  ingress:
    enabled: true
    className: nginx
    annotations:
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: &host dex.auth.devmem.ru
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - *host
        secretName: null
  serviceMonitor:
    enabled: true
