---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - all.yaml
configMapGenerator:
  - name: loki-promtail-dashboard
    files:
      - loki-promtail-dashboard.json=https://raw.githubusercontent.com/monitoring-mixins/website/master/assets/promtail/dashboards/promtail.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    grafana_folder: Loki
  labels:
    grafana_dashboard: "1"
