consul:
  global:
    name: consul
    image: hashicorp/consul:1.17.1
    # renovate: datasource=docker versioning=docker
    imageK8S: hashicorp/consul-k8s-control-plane:1.3.1
    acls:
      manageSystemACLs: true
    metrics:
      enabled: true
      enableAgentMetrics: true
  server:
    enabled: true
    replicas: 3
    storage: 1Gi
    storageClass: longhorn-sts
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    extraConfig: |
      {
        "leave_on_terminate": true,
        "telemetry": {
          "prometheus_retention_time": "1m",
          "disable_hostname": true
        }
      }
  ui:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: &host consul.k8s.devmem.ru
      tls:
        - hosts:
            - *host
          secretName: null
  connectInject:
    enabled: false
  tests:
    enabled: false
prometheus-consul-exporter:
  fullnameOverride: consul-exporter
  image:
    repository: prom/consul-exporter
    tag: v0.10.0
  consulServer: consul-server:8500
  serviceMonitor:
    enabled: true
